/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ouc.encrypt.view;

import com.ouc.encrypt.util.AESUtil;
import com.ouc.encrypt.util.FileUtil;
import com.ouc.encrypt.util.SimpleClient;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lenovo
 */
public class DecryptJInternalFrame extends javax.swing.JInternalFrame {
    private AESUtil aesUtil = new AESUtil();
    private FileUtil fUtil = new FileUtil();
    public static SimpleClient sUtil;
    private final static String AES = "AES";
    public List<Object> list = new ArrayList<Object>();

    /**
     * Creates new form DecipherJInternalFrame
     */
    public DecryptJInternalFrame() {
        initComponents();
        clearInput();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        decipherJPanel1 = new com.ouc.encrypt.view.DecryptJPanel();
        btnSearchKey = new javax.swing.JButton();
        txtKeyDir = new javax.swing.JTextField();
        btnDecrypt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblList = new javax.swing.JTable();
        btnSearchList = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        txtSaveDir = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtWriter = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtClass = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();

        setClosable(true);
        setTitle("解密");

        decipherJPanel1.setPreferredSize(new java.awt.Dimension(832, 501));

        btnSearchKey.setFont(new java.awt.Font("幼圆", 0, 14)); // NOI18N
        btnSearchKey.setText("选择密钥");
        btnSearchKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchKeyActionPerformed(evt);
            }
        });

        btnDecrypt.setFont(new java.awt.Font("幼圆", 1, 14)); // NOI18N
        btnDecrypt.setText("确认解密");
        btnDecrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecryptActionPerformed(evt);
            }
        });

        tblList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblList);

        btnSearchList.setFont(new java.awt.Font("幼圆", 0, 14)); // NOI18N
        btnSearchList.setText("查询文件");
        btnSearchList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchListActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("幼圆", 0, 14)); // NOI18N
        jLabel1.setText("解密文件id：");

        txtId.setEnabled(false);

        btnSave.setFont(new java.awt.Font("幼圆", 0, 14)); // NOI18N
        btnSave.setText("保存路径");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ouc/encrypt/img/search2.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("幼圆", 0, 14)); // NOI18N
        jLabel2.setText("文件名：");

        txtTitle.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("幼圆", 0, 14)); // NOI18N
        jLabel4.setText("时间：");

        txtDate.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("幼圆", 0, 14)); // NOI18N
        jLabel5.setText("作者：");

        txtWriter.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("幼圆", 0, 14)); // NOI18N
        jLabel6.setText("密级：");

        txtClass.setEnabled(false);

        btnClear.setFont(new java.awt.Font("幼圆", 1, 14)); // NOI18N
        btnClear.setText("清空");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout decipherJPanel1Layout = new javax.swing.GroupLayout(decipherJPanel1);
        decipherJPanel1.setLayout(decipherJPanel1Layout);
        decipherJPanel1Layout.setHorizontalGroup(
            decipherJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, decipherJPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(decipherJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(decipherJPanel1Layout.createSequentialGroup()
                        .addComponent(btnSave)
                        .addGap(31, 31, 31)
                        .addComponent(txtSaveDir, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDecrypt))
                    .addGroup(decipherJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(decipherJPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(decipherJPanel1Layout.createSequentialGroup()
                            .addComponent(btnSearchKey)
                            .addGap(31, 31, 31)
                            .addComponent(txtKeyDir, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(152, 152, 152))
            .addGroup(decipherJPanel1Layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addGroup(decipherJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(decipherJPanel1Layout.createSequentialGroup()
                        .addComponent(btnSearchList)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(decipherJPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(decipherJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(decipherJPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(decipherJPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(64, 64, 64)
                .addGroup(decipherJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(decipherJPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtWriter, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(decipherJPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtClass, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnClear)
                .addGap(27, 27, 27))
        );
        decipherJPanel1Layout.setVerticalGroup(
            decipherJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(decipherJPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(decipherJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, decipherJPanel1Layout.createSequentialGroup()
                        .addComponent(btnSearchList)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(decipherJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(decipherJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearchKey)
                    .addComponent(txtKeyDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(decipherJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(txtSaveDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDecrypt))
                .addGroup(decipherJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(decipherJPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(decipherJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(decipherJPanel1Layout.createSequentialGroup()
                                .addGroup(decipherJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(decipherJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(decipherJPanel1Layout.createSequentialGroup()
                                .addGroup(decipherJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtWriter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(decipherJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(39, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, decipherJPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClear)
                        .addGap(36, 36, 36))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(decipherJPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(decipherJPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // 选择解密密钥文件
    private void btnSearchKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchKeyActionPerformed
        JFileChooser openfile = new JFileChooser();//文件选择对话框
        FileFilter filter = new FileNameExtensionFilter("所有文件", "doc", "docx", "txt", "xlsx", "pdf");
        openfile.addChoosableFileFilter(filter);//添加过滤器
        openfile.setFileFilter(filter);
        int i = openfile.showOpenDialog(this);
        if (i == JFileChooser.APPROVE_OPTION) {
            //jFileChooser.show(true);
            //输出绝对路径
            txtKeyDir.setText(openfile.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_btnSearchKeyActionPerformed
    
    // 显示id列表
    private void showOnTable(List<Object> list) {
         // 1. 获取表格(tblProduct)模型
        DefaultTableModel dtm = (DefaultTableModel) this.tblList.getModel();
        // 2. 清空表格信息
        while (dtm.getRowCount() > 0) {
            dtm.removeRow(0);
        }
        // 3.显示数据
        for (Object s : list) {
            Vector vt = new Vector();
            vt.add(s.toString());
            dtm.addRow(vt);
        }
    }
    
    // 查询获得id列表
    private void btnSearchListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchListActionPerformed
        list = sUtil.fileList();
        // 显示在表格
        showOnTable(list);
    }//GEN-LAST:event_btnSearchListActionPerformed

    // 鼠标选中列表某行，该行信息显示到文本框
    private void tblListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListMouseClicked
        int row = this.tblList.getSelectedRow();
        // 根据row获取每列的值
        // 每行下标从0开始
        this.txtId.setText(this.tblList.getValueAt(row, 0)+"");
    }//GEN-LAST:event_tblListMouseClicked

    // 解密
    private void btnDecryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecryptActionPerformed
        String id = this.txtId.getText();
        String keyPath = this.txtKeyDir.getText(); // 获得密钥路径
        String key = fUtil.readTxtFile(keyPath); // 获取密钥
        String textPath = this.txtSaveDir.getText();
        //String ciphertext = fUtil.readTxtFile("C:\\Users\\Administrator\\Desktop\\fencryptfile.txt");
        
        if (id.isEmpty()){
            JOptionPane.showMessageDialog(this, "请选择解密文件id");
        }else if (keyPath.isEmpty()){
            JOptionPane.showMessageDialog(this, "请选择密钥");
        }else if (textPath.isEmpty()){
            JOptionPane.showMessageDialog(this, "请选择存储路径");
        }else{
            List <String> l = sUtil.readFile(id,key);
            String result = l.get(0);
            String cipherContent = l.get(1);
            String cipherTitle = l.get(5);
            if(result.equals("0")){// 解密文件
                try {
                    String clearContent = aesUtil.decrypt(key, cipherContent);
                    String clearTitle = aesUtil.decrypt(key, cipherTitle);
                    // 在面板上显示文件名等信息
                    if (clearTitle.substring(clearTitle.length()-4, clearTitle.length()).equals(".txt")){
                        if(!clearContent.isEmpty() && fUtil.writeTxtFile(textPath,clearTitle.substring(0,clearTitle.length()-4),clearContent) == true)
                            JOptionPane.showMessageDialog(this, "解密成功");
                        this.txtTitle.setText(clearTitle);
                    }else{
                        if(!clearContent.isEmpty() && fUtil.writeTxtFile(textPath,clearTitle,clearContent) == true)
                            JOptionPane.showMessageDialog(this, "解密成功");
                        this.txtTitle.setText(clearTitle+".txt");
                    }
                    this.txtWriter.setText(l.get(2));
                    this.txtDate.setText(l.get(3));
                    this.txtClass.setText(l.get(4));
                }catch (Exception e){
                    JOptionPane.showMessageDialog(this, "解密失败");
                }
            }else if(result.equals("1")){
                JOptionPane.showMessageDialog(this, "权限不足");
            }else if(result.equals("2")){
                JOptionPane.showMessageDialog(this, "文件不存在");
            }else if(result.equals("3")){
                JOptionPane.showMessageDialog(this, "网络异常");
            }
        }
    }//GEN-LAST:event_btnDecryptActionPerformed
    
    // 清空面板信息
    public void clearInput(){
        this.txtId.setText("");
        this.txtKeyDir.setText("");
        this.txtSaveDir.setText("");
        // 1. 获取表格(tblList)模型
        DefaultTableModel dtm = (DefaultTableModel) this.tblList.getModel();
        // 2. 清空表格信息
        while (dtm.getRowCount() > 0) {
            dtm.removeRow(0);
        }
        this.txtClass.setText("");
        this.txtDate.setText("");
        this.txtTitle.setText("");
        this.txtWriter.setText("");
    }

    // 选择解密后的文件保存路径
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        JFileChooser jf = new JFileChooser();
        jf.setFileSelectionMode(JFileChooser.SAVE_DIALOG | JFileChooser.DIRECTORIES_ONLY);
        jf.showDialog(null, null);
        File fi = jf.getSelectedFile();
        String f = fi.getAbsolutePath() + "\\";
        this.txtSaveDir.setText(f);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearInput();
    }//GEN-LAST:event_btnClearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDecrypt;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearchKey;
    private javax.swing.JButton btnSearchList;
    private com.ouc.encrypt.view.DecryptJPanel decipherJPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblList;
    private javax.swing.JTextField txtClass;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtKeyDir;
    private javax.swing.JTextField txtSaveDir;
    private javax.swing.JTextField txtTitle;
    private javax.swing.JTextField txtWriter;
    // End of variables declaration//GEN-END:variables
}
