/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ouc.encrypt.view;
import com.ouc.encrypt.util.FileUtil;
import com.ouc.encrypt.util.SimpleClient;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lenovo
 */
public class DeleteJInternalFrame extends javax.swing.JInternalFrame {
    private FileUtil fUtil = new FileUtil();
    public static SimpleClient sUtil;
    public List<Object> list = new ArrayList<Object>();
    private final static String AES = "AES";
    
    /**
     * Creates new form DecipherJInternalFrame
     */
    public DeleteJInternalFrame() {
        initComponents();
        clearInput();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        decipherJPanel1 = new com.ouc.encrypt.view.DecryptJPanel();
        btnSearchKey = new javax.swing.JButton();
        txtdir = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblList = new javax.swing.JTable();
        btnSearchList = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnDelete1 = new javax.swing.JButton();

        setClosable(true);
        setTitle("删除");

        decipherJPanel1.setPreferredSize(new java.awt.Dimension(832, 501));

        btnSearchKey.setFont(new java.awt.Font("幼圆", 0, 14)); // NOI18N
        btnSearchKey.setText("选择密钥");
        btnSearchKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchKeyActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("幼圆", 1, 14)); // NOI18N
        btnDelete.setText("确认删除");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        tblList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblList);

        btnSearchList.setFont(new java.awt.Font("幼圆", 0, 14)); // NOI18N
        btnSearchList.setText("查询文件");
        btnSearchList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchListActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("幼圆", 0, 14)); // NOI18N
        jLabel1.setText("删除文件id：");

        txtId.setEnabled(false);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ouc/encrypt/img/search2.png"))); // NOI18N

        btnDelete1.setFont(new java.awt.Font("幼圆", 1, 14)); // NOI18N
        btnDelete1.setText("清空");
        btnDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelete1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout decipherJPanel1Layout = new javax.swing.GroupLayout(decipherJPanel1);
        decipherJPanel1.setLayout(decipherJPanel1Layout);
        decipherJPanel1Layout.setHorizontalGroup(
            decipherJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(decipherJPanel1Layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(178, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, decipherJPanel1Layout.createSequentialGroup()
                .addGroup(decipherJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(decipherJPanel1Layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addGroup(decipherJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(decipherJPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(decipherJPanel1Layout.createSequentialGroup()
                                .addComponent(btnSearchKey)
                                .addGap(18, 18, 18)
                                .addComponent(txtdir, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDelete))
                    .addGroup(decipherJPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSearchList)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(decipherJPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDelete1)
                        .addGap(13, 13, 13)))
                .addGap(174, 174, 174))
        );
        decipherJPanel1Layout.setVerticalGroup(
            decipherJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(decipherJPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(decipherJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearchList, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(decipherJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(decipherJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearchKey)
                    .addComponent(txtdir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete))
                .addGap(30, 30, 30)
                .addComponent(btnDelete1)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(decipherJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(decipherJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // 选择解密密钥文件
    private void btnSearchKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchKeyActionPerformed
        JFileChooser openfile = new JFileChooser();//文件选择对话框
        FileFilter filter = new FileNameExtensionFilter("所有文件", "doc", "docx", "txt", "xlsx", "pdf");
        openfile.addChoosableFileFilter(filter);//添加过滤器
        openfile.setFileFilter(filter);
        int i = openfile.showOpenDialog(this);
        if (i == JFileChooser.APPROVE_OPTION) {
            //jFileChooser.show(true);
            //输出绝对路径
            txtdir.setText(openfile.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_btnSearchKeyActionPerformed
    
    // 显示id列表
    private void showOnTable(List<Object> list) {
         // 1. 获取表格(tblProduct)模型
        DefaultTableModel dtm = (DefaultTableModel) this.tblList.getModel();
        // 2. 清空表格信息
        while (dtm.getRowCount() > 0) {
            dtm.removeRow(0);
        }
        // 3.显示数据
        for (Object s : list) {
            Vector vt = new Vector();
            vt.add(s.toString());
            dtm.addRow(vt);
        }
    }
    
    // 查询获得id列表
    private void btnSearchListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchListActionPerformed
        list = sUtil.fileList();
        //3 显示在表格
        showOnTable(list);
    }//GEN-LAST:event_btnSearchListActionPerformed

    // 鼠标选中列表某行，该行信息显示到文本框
    private void tblListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListMouseClicked
        int row = this.tblList.getSelectedRow();
        // 根据row获取每列的值
        // 每行下标从0开始
        this.txtId.setText(this.tblList.getValueAt(row, 0)+"");
    }//GEN-LAST:event_tblListMouseClicked

    
    // 删除
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int answer =  JOptionPane.showConfirmDialog(this, "您确定要删除该文件吗？");
        if(answer == JOptionPane.YES_OPTION){
        // 1 获取删除编号
        String id = this.txtId.getText();
        String path = this.txtdir.getText();
        String key = fUtil.readTxtFile(path);
        if (id.isEmpty()){
            JOptionPane.showMessageDialog(this, "请选择删除文件id");
        }else if (path.isEmpty()){
            JOptionPane.showMessageDialog(this, "请选择密钥");
        }else{
            // 调用业务
            int result = sUtil.deleFile(id,key);
            if(result == 0){
                JOptionPane.showMessageDialog(this, "删除成功");
            }else if(result == 1){
                JOptionPane.showMessageDialog(this, "权限不足");
            }else if(result == 2){
                JOptionPane.showMessageDialog(this, "文件不存在");
            }else if(result == 3){
                JOptionPane.showMessageDialog(this, "网络异常");
            }
            // 清空面板信息
            clearInput();
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelete1ActionPerformed
        clearInput();
    }//GEN-LAST:event_btnDelete1ActionPerformed
    
    // 清空面板信息
    public void clearInput(){
        this.txtId.setText("");
        this.txtdir.setText("");
        // 1. 获取表格(tblList)模型
        DefaultTableModel dtm = (DefaultTableModel) this.tblList.getModel();
        // 2. 清空表格信息
        while (dtm.getRowCount() > 0) {
            dtm.removeRow(0);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDelete1;
    private javax.swing.JButton btnSearchKey;
    private javax.swing.JButton btnSearchList;
    private com.ouc.encrypt.view.DecryptJPanel decipherJPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblList;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtdir;
    // End of variables declaration//GEN-END:variables
}
