/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ouc.encrypt.view;

import com.ouc.encrypt.util.SimpleClient;
import com.ouc.encrypt.util.StringUtil;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author lenovo
 */
public class LoginJFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginJFrame
     */
    public LoginJFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginJPanel1 = new com.ouc.encrypt.view.LoginJPanel();
        loginJPanel2 = new com.ouc.encrypt.view.LoginJPanel();
        jLabel1 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnregist = new javax.swing.JButton();
        btnlogin = new javax.swing.JButton();
        txtpassword = new javax.swing.JPasswordField();

        javax.swing.GroupLayout loginJPanel1Layout = new javax.swing.GroupLayout(loginJPanel1);
        loginJPanel1.setLayout(loginJPanel1Layout);
        loginJPanel1Layout.setHorizontalGroup(
            loginJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        loginJPanel1Layout.setVerticalGroup(
            loginJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(Toolkit.getDefaultToolkit().getImage("1.jpg") );
        setPreferredSize(new java.awt.Dimension(720, 540));

        loginJPanel2.setPreferredSize(new java.awt.Dimension(720, 540));

        jLabel1.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("用户名：");

        jLabel2.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 204));
        jLabel2.setText("密码：");

        btnregist.setFont(new java.awt.Font("幼圆", 1, 18)); // NOI18N
        btnregist.setText("注册");
        btnregist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistActionPerformed(evt);
            }
        });

        btnlogin.setFont(new java.awt.Font("幼圆", 1, 18)); // NOI18N
        btnlogin.setText("登录");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginJPanel2Layout = new javax.swing.GroupLayout(loginJPanel2);
        loginJPanel2.setLayout(loginJPanel2Layout);
        loginJPanel2Layout.setHorizontalGroup(
            loginJPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginJPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginJPanel2Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(btnregist)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnlogin)
                .addGap(128, 128, 128))
        );
        loginJPanel2Layout.setVerticalGroup(
            loginJPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginJPanel2Layout.createSequentialGroup()
                .addContainerGap(368, Short.MAX_VALUE)
                .addGroup(loginJPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(loginJPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnlogin)
                    .addComponent(btnregist))
                .addGap(94, 94, 94))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginJPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginJPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        //1.获取登录信息
        // 登录
        //获取用户名和密码
        String usname = this.txtusername.getText().trim();
        char[] pswd = this.txtpassword.getPassword();
        String password = new String(pswd);
        //调用业务类
        //非空验证
        if (StringUtil.checkLength(usname) == false) {
            JOptionPane.showMessageDialog(this, "用户名不能为空！");
            return;
        }
        if (StringUtil.checkLength(password) == false) {
            JOptionPane.showMessageDialog(this, "密码不能为空！");
            return;
        }
        SimpleClient s = new SimpleClient(usname, password);
        int i = s.logIn();
        if (i == 0) {
            // 打开主界面，并将登录对象传递给主界面
            // 先传值
            MainFrame.s = s;
            System.out.println("登录成功！");
            MainFrame mf = new MainFrame();
            mf.setVisible(true);
            this.dispose(); //关闭登录界面 
        }
        if (i == -2) {
            JOptionPane.showMessageDialog(this, "当前用户未注册或密码错误！");
            //清空面板信息
            clearInput();
            return;
        }if (i == -1 || i== -3) {
            JOptionPane.showMessageDialog(this, "登录失败！");
            //清空面板信息
            clearInput();
            return;
        }
        if (i == 3) {
            JOptionPane.showMessageDialog(this, "网络错误！");
            //清空面板信息
            clearInput();
        }
    }//GEN-LAST:event_btnloginActionPerformed

    private void clearInput() {
        this.txtusername.setText("");
        this.txtpassword.setText("");
    }

    private void btnregistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistActionPerformed
        // TODO add your handling code here:
        RegisterFrame rf = new RegisterFrame();
        rf.setVisible(true);
        this.dispose(); //关闭登录界面
    }//GEN-LAST:event_btnregistActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlogin;
    private javax.swing.JButton btnregist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private com.ouc.encrypt.view.LoginJPanel loginJPanel1;
    private com.ouc.encrypt.view.LoginJPanel loginJPanel2;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
